### ISSUE TITLE
Proper file loading

### ISSUE THREAD

**Issue by AConsolePeasant** [AConsolePeasant/EO-Flashcards#3]
`Dim english As String() = System.IO.File.ReadAllLines("C:\Users\ACP\Documents\GitHub\EO-Flashcards\EO-Flashcards\EO-Flashcards\Resources\engout.txt")`
    `Dim esperanto As String() = System.IO.File.ReadAllLines("C:\Users\ACP\Documents\GitHub\EO-Flashcards\EO-Flashcards\EO-Flashcards\Resources\espout.txt")`

This means the file can only be read from that single directory, and is hard for the user to set it up, and will only work on my pc
We could have a dialog that pops up asking for the two files, or maybe include it in the program.

I've looked into setting up the automatic way with Resources, but it's looking impossible.

> https://github.com/AConsolePeasant/EO-Flashcards/blob/master/EO-Flashcards/EO-Flashcards/frmArcade.vb

@domacikolaci, know anything?

**Comment by afogal** [comment]
http://stackoverflow.com/questions/25195445/how-do-i-specify-relative-file-path-in-vb-net ?
